In [1]:
import os
import numpy as np
import pandas as pd
os.chdir("C:\Users\User\Downloads")
# Import the necessary modules
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv("fake_or_real_news.csv")

In [35]:


#print(df.head())


y = df.label
#print(y)


X_train, X_test, y_train, y_test = train_test_split(df["text"],y,test_size=0.33,
                                    random_state=53)


count_vectorizer = CountVectorizer(stop_words="english")


count_train = count_vectorizer.fit_transform(X_train.values)


count_test = count_vectorizer.transform(X_test.values)


print(count_vectorizer.get_feature_names()[:1000])
print(count_train.toarray())

[u'00', u'000', u'0000', u'00000031', u'000035', u'00006', u'0001', u'0001pt', u'000ft', u'000km', u'001', u'0011', u'002', u'003', u'004', u'006', u'006s', u'007', u'007s', u'008', u'008s', u'009', u'0099', u'00am', u'00p', u'00pm', u'01', u'010', u'013', u'014', u'015', u'016', u'018', u'01am', u'02', u'020', u'022', u'023', u'024', u'025', u'027', u'028', u'02welcome', u'03', u'031', u'032', u'0325', u'033', u'034', u'035', u'037', u'039', u'03eb', u'04', u'040', u'0400', u'042', u'044', u'048', u'049', u'04pm', u'05', u'0509245d29', u'052', u'056', u'06', u'062', u'066', u'068', u'06pm', u'07', u'0700', u'075', u'076', u'079', u'07dryempjx', u'08', u'080', u'081', u'082', u'084', u'089', u'0891', u'09', u'098263', u'09am', u'09pm', u'0_jgdktlmn', u'0a_merrill', u'0d', u'0fjjvowyhg8qtskiz', u'0h4at2yetra17uxetni02ls2jeg0mty45jrcu7mrzsrpcbq464i', u'0hq3vb2giv', u'0in', u'0jsn6pjkan', u'0oeekvljlt', u'0pt', u'0t5', u'0txrbwvobzz4fi5nksw6k5a6cxzbb3juxthmdiz93cby8gvrqiypzhajvjnt2', u'0w

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [39]:
corpus = [
    'This is the first.',
   'This is the second.'
 ]
v = count_vectorizer.fit_transform(corpus)
print(v) 
print(count_vectorizer.inverse_transform(v))
print(count_vectorizer.get_feature_names())

  (1, 0)	1
[array([], dtype='<U6'), array([u'second'], dtype='<U6')]
[u'second']


In [18]:

from sklearn.feature_extraction.text import TfidfVectorizer


tfidf_vectorizer = TfidfVectorizer(stop_words="english",max_df=0.7)


tfidf_train = tfidf_vectorizer.fit_transform(X_train.values)


tfidf_test = tfidf_vectorizer.transform(X_test.values)


print(tfidf_vectorizer.get_feature_names()[:10])


print(tfidf_train.A[:5])


[u'00', u'000', u'0000', u'00000031', u'000035', u'00006', u'0001', u'0001pt', u'000ft', u'000km']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [19]:
count_df = pd.DataFrame(count_train.A, columns=count_vectorizer.get_feature_names())
print(count_df)


tfidf_df = pd.DataFrame(tfidf_train.A, columns=tfidf_vectorizer.get_feature_names())


print(count_df.head())


print(tfidf_df.head())


difference = set(count_df.columns) - set(tfidf_df.columns)
print(difference)


print(count_df.equals(tfidf_df))


      00  000  0000  00000031  000035  00006  0001  0001pt  000ft  000km  \
0      0    0     0         0       0      0     0       0      0      0   
1      0    0     0         0       0      0     0       0      0      0   
2      0    0     0         0       0      0     0       0      0      0   
3      0    0     0         0       0      0     0       0      0      0   
4      0    0     0         0       0      0     0       0      0      0   
5      0    1     0         0       0      0     0       0      0      0   
6      0    0     0         0       0      0     0       0      0      0   
7      0    0     0         0       0      0     0       0      0      0   
8      0    1     0         0       0      0     0       0      0      0   
9      0    1     0         0       0      0     0       0      0      0   
10     0    0     0         0       0      0     0       0      0      0   
11     0    0     0         0       0      0     0       0      0      0   
12     0    

   00  000  0000  00000031  000035  00006  0001  0001pt  000ft  000km  ...    \
0   0    0     0         0       0      0     0       0      0      0  ...     
1   0    0     0         0       0      0     0       0      0      0  ...     
2   0    0     0         0       0      0     0       0      0      0  ...     
3   0    0     0         0       0      0     0       0      0      0  ...     
4   0    0     0         0       0      0     0       0      0      0  ...     

   حلب  عربي  عن  لم  ما  محاولات  من  هذا  والمرضى  ยงade  
0    0     0   0   0   0        0   0    0        0      0  
1    0     0   0   0   0        0   0    0        0      0  
2    0     0   0   0   0        0   0    0        0      0  
3    0     0   0   0   0        0   0    0        0      0  
4    0     0   0   0   0        0   0    0        0      0  

[5 rows x 56922 columns]
    00  000  0000  00000031  000035  00006  0001  0001pt  000ft  000km  ...    \
0  0.0  0.0   0.0       0.0     0.0    0.0   0

In [20]:

from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics


nb_classifier = MultinomialNB()


nb_classifier.fit(count_train, y_train)


pred =nb_classifier.predict(count_test)


score = metrics.accuracy_score(y_test, pred)
print(score)


cm = metrics.confusion_matrix(y_test, pred, labels=["FAKE","REAL"])
print(cm)


0.893352462936394
[[ 865  143]
 [  80 1003]]


In [21]:

nb_classifier = MultinomialNB()


nb_classifier.fit(tfidf_train, y_train)


pred = nb_classifier.predict(tfidf_test)


score = metrics.accuracy_score(y_test, pred)
print(score)


cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
print(cm)


0.8565279770444764
[[ 739  269]
 [  31 1052]]


In [24]:
alphas = np.arange(0, 1, .1)
print(alphas)

def train_and_predict(alpha):
    
    nb_classifier = MultinomialNB(alpha=alpha)
    
    nb_classifier.fit(tfidf_train, y_train)
   
    pred = nb_classifier.predict(tfidf_test)
    
    score = metrics.accuracy_score(y_test, pred)
    return score


for alpha in alphas:
    print('Alpha: ', alpha)
    print('Score: ', train_and_predict(alpha))
    print()
    

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
('Alpha: ', 0.0)
('Score: ', 0.8813964610234337)
()
('Alpha: ', 0.1)
('Score: ', 0.8976566236250598)
()
('Alpha: ', 0.2)
('Score: ', 0.8938307030129125)
()
('Alpha: ', 0.30000000000000004)
('Score: ', 0.8900047824007652)
()
('Alpha: ', 0.4)
('Score: ', 0.8857006217120995)
()
('Alpha: ', 0.5)
('Score: ', 0.8842659014825442)
()
('Alpha: ', 0.6000000000000001)
('Score: ', 0.874701099952176)
()
('Alpha: ', 0.7000000000000001)
('Score: ', 0.8703969392635102)
()
('Alpha: ', 0.8)
('Score: ', 0.8660927785748446)
()
('Alpha: ', 0.9)
('Score: ', 0.8589191774270684)
()


In [23]:

class_labels = nb_classifier.classes_


feature_names = tfidf_vectorizer.get_feature_names()


feat_with_weights = sorted(zip(nb_classifier.coef_[0], feature_names))


print(class_labels[0], feat_with_weights[:20])


print(class_labels[1], feat_with_weights[-20:])


('FAKE', [(-11.316312804238807, u'0000'), (-11.316312804238807, u'000035'), (-11.316312804238807, u'0001'), (-11.316312804238807, u'0001pt'), (-11.316312804238807, u'000km'), (-11.316312804238807, u'0011'), (-11.316312804238807, u'006s'), (-11.316312804238807, u'007'), (-11.316312804238807, u'007s'), (-11.316312804238807, u'008s'), (-11.316312804238807, u'0099'), (-11.316312804238807, u'00am'), (-11.316312804238807, u'00p'), (-11.316312804238807, u'00pm'), (-11.316312804238807, u'014'), (-11.316312804238807, u'015'), (-11.316312804238807, u'018'), (-11.316312804238807, u'01am'), (-11.316312804238807, u'020'), (-11.316312804238807, u'023')])
('REAL', [(-7.742481952533027, u'states'), (-7.717550034444668, u'rubio'), (-7.703583809227384, u'voters'), (-7.654774992495461, u'house'), (-7.649398936153309, u'republicans'), (-7.6246184189367, u'bush'), (-7.616556675728882, u'percent'), (-7.545789237823644, u'people'), (-7.516447881078008, u'new'), (-7.448027933291952, u'party'), (-7.41114841020